version: "2"
services:

  database:
    image: mariadb:10
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=veryhardpassword
      - MYSQL_DATABASE=okbs
      - MYSQL_USER=aaksit
      - MYSQL_PASSWORD=veryhardpassword
    volumes:
      - db-data:/var/lib/mysql
      - ${PWD}/okbs.sql:/docker-entrypoint-initdb.d/okbs.sql:ro
    #ports:
    #  - "3306:3306"
    restart: always


  application:
    image: okbs-appointment
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${PWD}/src:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - database

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - database

volumes:
  db-data: